### ISSUE TITLE
scope callbacks vs. visibility groups

### ISSUE THREAD

**Issue by bkconrad** [bkconrad/wasabi#30]
So, should we keep both around since they can coexist?

I think scope callbacks complicate the mental model of Wasabi without adding much power over visibility groups (in fact groups seem easier, simpler, and more powerful). LOC-wise, you can count the difference on one hand, I just feel bad about keeping a redundant mechanism around  long-term.

**Comment by mreinstein** [comment]
I think we should update the doc to mention scope callbacks are deprecated, and at some point in the future remove it (maybe for 1.0.0?)
